version: '3.9'

services:
  web:
    build: .
    image: currantino/run_text_project-web:latest
    entrypoint:
      - /app/entrypoint.sh
    ports:
      - "0.0.0.0:80:80"
    env_file:
      - .web.env
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy

  postgres:
    image: postgres:15
    env_file:
      - .postgres.env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgres" ]
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 1s
    volumes:
      - ~/private/var/lib/postgresql:/var/lib/postgresql

  minio:
    image: minio/minio:RELEASE.2023-11-20T22-40-07Z-cpuv1
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .minio.env
    volumes:
      - ~/private/minio/data:/data
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      start_period: 3s
      interval: 3s
      timeout: 3s
      retries: 3

